- name: Copy module in Ansible
  hosts: all
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present

    - name: Copy file to remote server
      copy:
        src: ./index.html
        dest: /var/www/html/index.html

    - name: start apache2 service
      service:
        name: apache2
        state: restarted
        enabled: true    
