- name: installation file
  hosts: hostall
  tasks:
    - name: install apache
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: install httpd
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
      
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"