- name: Local and globle variables
  hosts: hostall
  vars:
    movie: "Batman"
  tasks:
    - name: this is first task
      debug:
        msg: "The {{ movie }} movie is good"
    - name: this is second task
      debug:
        msg: "The {{ movie }} movie is good"
      vars:
        movie: "Avengers"
    - name: this is third task
      debug:
        msg: "The {{ movie }} movie is good"